### ISSUE TITLE
I can't get it to not have hints on the ground

### ISSUE THREAD

**Issue by alexUnd** [asrbic/Procedural_Ore_Generator#10]
tried with any parameters, but the hints are still there. surfaceHintMaps false, true, surfaceHintProbability 0.1, 001 and so on

**Comment by alexUnd** [comment]
No manipulation with the parameters, colors, transparency, etc. helps:
In files everywhere, we just delete color information
Ore Value="1" Type="Iron_02" Start="30" Depth="4" TargetColor="#616c83" ColorInfluence="15"  to 
Ore Value="1" Type="Iron_02" Start="30" Depth="4"
and that's it . No more stains, like after the Tide. And the ore is still there.

**Comment by asrbic** [comment]
Strange, in my testing setting surfaceHintMaps to false made them not appear. Perhaps that's broken now. The hints locations are determined by the _add.png images. Setting surfaceHintMaps to false should stop these from being generated. If they're not present in the mod then the hints shouldn't be there. Perhaps these files were included from a previous run of the generator?
