### ISSUE TITLE
Using the ore generator for modded / non-vanilla ores

### ISSUE THREAD

**Issue by g46492** [asrbic/Procedural_Ore_Generator#19]
Hey there, I really like your ore generator. (And yes, snake ore generation is kind of cool)
Would the ore generator also work for modded ores if they are added to the IDs and have a valid / matching ore color key?
(<ColorKey Hex="#??????"/>)

**Comment by asrbic** [comment]
Sorry for the delay, I thought I had already replied to this issue.

Yep, modded ores will work fine - just need to reference the appropriate type (eg. "type": "Iron_02") in the config. This type is found in the VoxelMaterialDefinitions of the modded ore.

**Comment by g46492** [comment]
Sweet!
