### ISSUE TITLE
Missing run.bat

### ISSUE THREAD

**Issue by Mastery567** [asrbic/Procedural_Ore_Generator#2]
Hi,

the readme tells to execute "run.bat", but there is no such file.
Am I missing a step (new to github)

Thanks in advance =)

**Comment by asrbic** [comment]
Hello,

Did you download "Procedural_Ore_Generator.zip" from "https://github.com/asrbic/Procedural_Ore_Generator/releases"? That should have the run.bat in it. Perhaps you downloaded the source code instead?

**Comment by Mastery567** [comment]
Yeah I only checked out the sourcode on github.
Thanks =)
