### ISSUE TITLE
add support for separate  definition files files (aka add Pertam and Triton)

### ISSUE THREAD

**Issue by ttr** [asrbic/Procedural_Ore_Generator#4]
Hey,
recent addon added one planet - Triton - earth alike in terms of difficulty) and Pertam - moon.

Extending config.json is easy but problem is that those two are in separate files, named after them self's.

Any chance to extend your app to have planetGeneratorDefinitionsPath as array of files so we can specify all 3 of them?

**Comment by asrbic** [comment]
I've added support for this with the latest release (0.16). You should be able to use "planetGeneratorDefinitionsPathArray". Pertam and Triton also had a different xml structure so I've added support for that too.

**Comment by asrbic** [comment]
Better to grab release 0.17 actually. There was a critical bug in 0.16.

**Comment by ttr** [comment]
cool. will close this ticket now.
