### ISSUE TITLE
Earth with no ore nodes

### ISSUE THREAD

**Issue by Immoxz** [asrbic/Procedural_Ore_Generator#5]
First i thought that there is realy wide spead of ore nodes. but it trun out after 10 hours of playing that there are non. only boulders.

here is a log:

12:49:05.857 [pool-2-thread-4] INFO  Main - Europa:	Writing ore data to map images in: .\PlanetDataFiles\Europa
12:49:05.860 [pool-2-thread-1] INFO  Generator - EarthLike:		Tiles generated for ore Gold_01 (id:168) with testColour ffffd800 : 0
12:49:05.860 [pool-2-thread-1] INFO  Generator - EarthLike:		Tiles generated for ore Silicon_01 (id:48) with testColour ffffffff : 11416
12:49:05.861 [pool-2-thread-1] INFO  Generator - EarthLike:		Tiles generated for ore Silver_01 (id:96) with testColour ffa0a0a0 : 157
12:49:05.861 [pool-2-thread-1] INFO  Generator - EarthLike:		Tiles generated for ore Iron_02 (id:1) with testColour ffe00000 : 52732
12:49:05.861 [pool-2-thread-1] INFO  Generator - EarthLike:		Tiles generated for ore Platinum_01 (id:192) with testColour ff5d188e : 0
12:49:05.862 [pool-2-thread-1] INFO  Generator - EarthLike:		Tiles generated for ore Nickel_01 (id:24) with testColour ffff9741 : 8566
12:49:05.862 [pool-2-thread-1] INFO  Generator - EarthLike:		Tiles generated for ore Magnesium_01 (id:120) with testColour ff958cff : 4974
12:49:05.862 [pool-2-thread-1] INFO  Generator - EarthLike:		Tiles generated for ore Uraninite_01 (id:144) with testColour ff00ff00 : 13
12:49:05.863 [pool-2-thread-1] INFO  Generator - EarthLike:		Tiles generated for ore Cobalt_01 (id:72) with testColour ff0033ff : 22182
12:49:05.863 [pool-2-thread-1] INFO  Main - EarthLike:	Tiles generated:100040
12:49:05.863 [pool-2-thread-1] INFO  Main - EarthLike:	Writing ore data to map images in: .\PlanetDataFiles\EarthLike
12:49:05.864 [main] ERROR Main - Exception occurred: 
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_271]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_271]
	at core.Main.generate(Main.java:120) ~[Procedural_Ore_Generator.jar:?]
	at core.Main.run(Main.java:75) ~[Procedural_Ore_Generator.jar:?]
	at core.Main.main(Main.java:37) [Procedural_Ore_Generator.jar:?]
Caused by: java.lang.NullPointerException
	at core.Main.lambda$0(Main.java:111) ~[Procedural_Ore_Generator.jar:?]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:1.8.0_271]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:1.8.0_271]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_271]
12:49:05.869 [main] INFO  Main - Done. Press the ENTER key to exit
12:49:05.968 [pool-2-thread-5] INFO  Main - Alien:	Generating ore tiles with effective ore configs:

**Comment by asrbic** [comment]
Looks like there was a bug that didn't show itself when I was testing the last release. Have fixed it in the new release: 0.17. Sorry you wasted all that time - the generator should now make it quite clear when it fails like that.

**Comment by Immoxz** [comment]
It should fix problem, with throwing exception and continue working, but what about throwing null?

**Comment by asrbic** [comment]
I also fixed the cause of the NullPointerException. It should no longer be thrown.
