### ISSUE TITLE
Mod partially skipped Error

### ISSUE THREAD

**Issue by 2000game** [asrbic/Procedural_Ore_Generator#6]
When trying to make a new star system with the mod I get the following errors:

MOD_CRITICAL_ERROR: ProdOreGen, in file: 
MOD PARTIALLY SKIPPED, LOADED ONLY 1/6 PHASES, Following Error occured:
Object reference not set to an instance of an object.
Sandbox.Game
   at Sandbox.Definitions.MyDefinitionManager.LoadDefinitions(List`1 contexts, List`1 definitionSets, Boolean failOnDebug, Boolean isPreload)
MOD_CRITICAL_ERROR: ProdOreGen, in file: 
MOD PARTIALLY SKIPPED, LOADED ONLY 2/6 PHASES, Following Error occured:
Object reference not set to an instance of an object.
Sandbox.Game
   at Sandbox.Definitions.MyDefinitionManager.LoadDefinitions(List`1 contexts, List`1 definitionSets, Boolean failOnDebug, Boolean isPreload)
MOD_CRITICAL_ERROR: ProdOreGen, in file: 
MOD PARTIALLY SKIPPED, LOADED ONLY 3/6 PHASES, Following Error occured:
Object reference not set to an instance of an object.
Sandbox.Game
   at Sandbox.Definitions.MyDefinitionManager.LoadDefinitions(List`1 contexts, List`1 definitionSets, Boolean failOnDebug, Boolean isPreload)
MOD_CRITICAL_ERROR: ProdOreGen, in file: 
MOD PARTIALLY SKIPPED, LOADED ONLY 4/6 PHASES, Following Error occured:
Object reference not set to an instance of an object.
Sandbox.Game
   at Sandbox.Definitions.MyDefinitionManager.LoadDefinitions(List`1 contexts, List`1 definitionSets, Boolean failOnDebug, Boolean isPreload)
MOD_CRITICAL_ERROR: ProdOreGen, in file: 
MOD PARTIALLY SKIPPED, LOADED ONLY 5/6 PHASES, Following Error occured:
Object reference not set to an instance of an object.
Sandbox.Game
   at Sandbox.Definitions.MyDefinitionManager.LoadDefinitions(List`1 contexts, List`1 definitionSets, Boolean failOnDebug, Boolean isPreload)
MOD_CRITICAL_ERROR: ProdOreGen, in file: 
MOD PARTIALLY SKIPPED, LOADED ONLY 6/6 PHASES, Following Error occured:
Object reference not set to an instance of an object.
Sandbox.Game
   at Sandbox.Definitions.MyDefinitionManager.LoadDefinitions(List`1 contexts, List`1 definitionSets, Boolean failOnDebug, Boolean isPreload)

I already tried reinstalling the game and deleting everything but the issue persists. I only changed the makeColouredMaps from True to false.

**Comment by asrbic** [comment]
I think this error is because Space Engineers expects the heightmaps to be in the same directory as the modded ore maps (PlanetDataFiles/<planet_name>/), even if the heightmaps for that planet are already present somewhere else. These are the greyscale images with names like "up.png", "back.png". 

Probably the easiest way to be sure is to copy all the PlanetDataFiles of the planets you want to change the ores of to a new folder then copy the output of the Procedural Ore Generator into that folder, overwriting any files.

**Comment by asrbic** [comment]
Just updated the readme to reflect this

**Comment by 2000game** [comment]
Since this didn't solve the issue for me I copied the files from the space engineers directory into a new mod. And didn't overwrite them with the procedural generated ones and I still get the same error.

**Comment by asrbic** [comment]
Right, in your test did you copy PlanetDataFiles/*, PlanetGeneratorDefinitions.sbc, Triton.sbc and Pertam.sbc from the Space Engineers directory?

**Comment by 2000game** [comment]
Yes, is the folder structure relevant? I tried 
```
"NameOfModFolder"
  "PlanetDataFiles"
     "Alien"
     "Earth"
     "etc"
  "Pertram.sbc"
  "Triton.sbc"
  "PlanetGeneratorDefinitions.sbc"

```
and
```
"NameOfModFolder"
  "Alien"
  "Earth"
  "etc"
  "Pertram.sbc"
  "Triton.sbc"
  "PlanetGeneratorDefinitions.sbc"

```
But I still get the same errors. I also tried disabling the dlcs though that didn't either.

**Comment by asrbic** [comment]
Looks like I omitted something else - all of the files in NameOfModFolder should be in a subfolder named "Data". Sorry about that. You have to replicate the folder structure in SpaceEngineers\Content. In our case, all the files we're changing are in Data\.
