### ISSUE TITLE
calculation of the total amount of each ore on the planet

### ISSUE THREAD

**Issue by alexUnd** [asrbic/Procedural_Ore_Generator#9]
Hi. What is the formula for calculating and what parameter to adjust the total amount of ore on the planet? I understand that the parameter surfaceArea is the number of tiles in each individual deposit. And the total amount of ore I do not understand how and where is set? With the parameter "p"? Can it be more than 1? thnks!

**Comment by asrbic** [comment]
The exact total can't be directly adjusted. It's a pretty silly algorithm really. Given the ores below:
```
iron    {p:60}
cobalt  {p:30}
gold    {p:10}
```
Assuming these are the only ores configured for a planet, then the algorithm will repeatedly and randomly select one of those three and draw a random patch of it. The "p" param is the chance that each one will be selected. All of the p values add up to 100 in this case so iron will be selected 60% of the time, cobalt 30% and gold 10% of the time. This will keep happening until "maxOrePatches" patches or "maxOreTiles" tiles are painted.

So the various settings on ores are more suggestions of what you'd like to be more popular and larger while maxOreTiles and maxOrePatches on planets tell the program when to stop randomly painting. 

"p" can be whatever you want - it might be easier to manage if you make all the "p" values for a planet add up to 1 or 100. Then each p value would be a percentage.

**Comment by alexUnd** [comment]
Thanks for the clarification. I also understood that the total number of fields should be adjusted with the parameter maxOrePatches. and the amount of ore in each of them by the parameter surfaceArea and Depth (but it is not included in the calculation). "p" regulates the ratios of ores among themselves on the planet
